### ISSUE TITLE
What are the objectives of this repo?

### ISSUE THREAD

**Issue by HitaloKun** [SpamWatch/SpamWatchBot#1]
Are there still plans for a SpamWatch bot?

**Comment by SitiSchu** [comment]
The official SpamWatch Telegram bot implementing the SpamWatch API. (could've just asked in the support chat btw :P)

**Comment by HitaloKun** [comment]
@SitiSchu no doubt spamwatch is the best Anti-Spam system available for Telegram, you're doing a great job. 😊
